---
- name: user | Ensure group exists
  ansible.builtin.group:
    name: "{{ wud_docker_group }}"
    gid: "{{ wud_docker_gid }}"
    state: present

- name: user | Ensure user exists with gid
  ansible.builtin.user:
    name: "{{ wud_docker_user }}"
    uid: "{{ wud_docker_uid }}"
    system: "{{ wud_docker_user_system | default(omit) }}"
    state: present
